# Generated by Django 5.2 on 2025-05-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('informacion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='almuerzos/')),
                ('tipo', models.CharField(choices=[('parrilla', 'Parrilla'), ('entrada', 'Entrada'), ('ensalada', 'Ensalada'), ('pasta', 'Pasta'), ('postre', 'Postre'), ('bebida', 'Bebida')], default='parrilla', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carnet', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=50)),
                ('identificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('parrilla', 'Especialidades a la Parrilla'), ('entradas', 'Entradas y Aperitivos'), ('ensaladas', 'Ensaladas'), ('pastas', 'Pastas Artesanales'), ('postres', 'Postres'), ('bebidas', 'Bebidas')], max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platillos/')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas', models.PositiveIntegerField()),
                ('grupo', models.CharField(blank=True, default='Ninguna', max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('dia_especial', models.CharField(blank=True, default='Ninguna', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
