# Generated by Django 5.2 on 2025-05-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
