# Generated by Django 5.2 on 2025-06-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_reserva_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almuerzo',
            name='informacion',
        ),
        migrations.AddField(
            model_name='almuerzo',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='almuerzo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platillos/'),
        ),
    ]
