# Generated by Django 5.2 on 2025-06-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_comentario_fecha_hora_alter_comentario_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default='Invitado', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pasada', 'Pasada')], default='activa', max_length=10),
        ),
    ]
