# Generated by Django 5.2 on 2025-06-19 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_reserva_nombre_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='puntuacion',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pais',
            field=models.CharField(max_length=100),
        ),
    ]
