# Generated by Django 5.2 on 2025-06-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.TextField(blank=True),
        ),
    ]
